#!/usr/bin/env bash


# add files that should be symlinked here
BASE_FILES=(
.tmux.conf
.vimrc
.zshrc
.shellibrc
.shellib
.ctags
.googlerc
.ipython/profile_default/ipython_config.py
.flake8
)

# add files that should be copied once here
EXTRA_FILES=(
.profile
.vimplugins
)

CUSTOM_FILES=(
customized/.profile
customized/.vimplugins
)

panic() { echo $@ 1>&2; exit 1; }

SCRIPT_DIR="`dirname $0`"
if source $SCRIPT_DIR/.shellib/shellib.sh;
then log "shellib loaded"
else panic "failed to load $SCRIPT_DIR/.shellib/shellib.sh"
fi

target_exists(){ test -e "$@" || test -L "$@";  }
file_exists()  { test -e "$@";                  }

create_link()  { ln -snr    "$1" "$2"; }
update_link()  { ln -snr -b "$1" "$2"; }

target_path(){
	if test `dirname "$1"` = "customized"
	then echo $TRG_DIR/`basename "$1"`
	else echo $TRG_DIR/$1
	fi
}

clean(){
	if $CLEAN; then
		trg="`target_path "$1"`"
		if file_exists "$trg"; then
			if backups=(`find "$trg"* -maxdepth 0 | grep -e "$trg[0-9~]\+"`)
			then rm ${backups[@]}; warn "removed backups: ${backups[@]}"
			fi
		else
			panic "internal error: cannot clean backups of non-existing links"
		fi
	fi
}

usage() {
	cat 1>&2 <<-EOF
	Usage: $0 [OPTIONS]

	Options:

	   --force             overwrite any existng links
	   --copy-customized   copy-once customized files instead of copying-once extra files
	   --link-customized   create links to customized files instead of copying extra files
      
	   --clean             remove backup files TRG_DIR/FILE[0-9~]+
	   --diff              show diff for updated or skipped files
	   --difftool          show diff using git's diff.tool
      
	   --help              show this usage info
	   --debug             more logging

	Files:

		Main files are:        ${BASE_FILES[@]}
		Copy-once files are:   ${EXTRA_FILES[@]}
		Customized files are:  ${CUSTOM_FILES[@]}

	EOF
}

errors=0
created=0
skipped=0
updated=0
files_updated=0
files_created=0
files_skipped=0

SRC_DIR=`readlink -f $(dirname "$0")` || panic "could not determine script dir"
TRG_DIR="$HOME"
TRG_DIR_EXPR='$HOME'

FORCE=false
CLEAN=false
DIFF=false
DIFF_CMD=diff
DIFF_TOOL=`git config diff.tool 2>/dev/null || echo diff`
LINK_FILES=(${BASE_FILES[@]})
test -z "$DEBUG" && DEBUG=false

# parse options
for opt in $@; do case $opt in
	--help)            usage; exit 1;;
	--link-customized) LINK_FILES=(${BASE_FILES[@]} ${CUSTOM_FILES[@]}); COPY_FILES=();;
	--copy-customized) LINK_FILES=(${BASE_FILES[@]}); COPY_FILES=(${CUSTOM_FILES[@]});;
	--clean)           CLEAN=true;;
	--force)           FORCE=true;;
	--debug)           DEBUG=true;;
	--difftool)        DIFF=true; DIFF_CMD="$DIFF_TOOL";;
	--diff)            DIFF=true;;
	*)                 ;;
esac done

# access target and source dirs
test -d "$TRG_DIR" || panic "TRG_DIR dir not found: $TRG_DIR"
cd "$SRC_DIR"      || panic "cannot access source dir: $SRC_DIR"

warn "using target dir: $TRG_DIR"

# create/update links
for src in ${LINK_FILES[@]}; do
	lnk="`target_path "$src"`"
	debug "processing link: $lnk -> $SRC_DIR/$src"
	if   ! file_exists $src; then

		(( errors++ )); warn "source file not found: $src"

	elif ! target_exists $lnk; then

		if create_link "$src" "$lnk"
		then (( created++ )); log  "created link: $lnk"; clean $lnk
		else (( errors++  )); warn "failed to create link: $lnk"
		fi

	else
		rl_src="`readlink -f "$src"`"
		rl_lnk="`readlink -f "$lnk"`"
		if test "$rl_src" = "$rl_lnk"
		then (( skipped++ )); log "link already up-to-date: $lnk -> $rl_src"
		elif $FORCE; then
			if update_link "$src" "$lnk"
			then (( updated++ )); log  "updated link: $lnk"; clean $lnk
			else (( errors++  )); warn "failed to update link: $lnk"
			fi
		else (( skipped++ )); log "skipping existing link: $lnk";
		fi
	fi

	debug -e $lnk* "\n"

done

# add customizable copy-once files
for src in ${COPY_FILES[@]}; do
	trg="`target_path $src`"
	if file_exists $trg;
	then (( files_skipped++ )); log "preserving existing file: $trg"
	elif cp "$src" "$trg"
	then (( files_created++ )); log "copied file: $trg"
	fi
	if $DIFF; then
		log "$DIFF_CMD $src $trg"
		$DIFF_CMD $src "$trg" 1>&2
	fi
done

# add/update source script
source_host="$TRG_DIR/.profile"
source_tag="# generated by shellib"
source_msg="(do not edit manually)"
source_script="source $TRG_DIR_EXPR/.shellib/shellib.sh"
source_line="$source_script $source_tag $source_msg"
SED_OPTS="--follow-symlinks -i"

if host_line=`grep "$source_tag" "$source_host"`; then

	if test "$host_line" = "$source_line"
	then source_status=skipped; log "source script already up-to-date, found source line '$source_line' in $source_host"
	elif sed $SED_OPTS "s@.*$source_tag.*@$source_line@" "$source_host"
	then source_status=updated; log "updated source script in profile: $source_host"; clean $source_host
	else (( errors++ )); warn "failed to update source script in profile: $source_host"
	fi


elif grep "shellib.sh" "$source_host" 1> /dev/null; then

	if $FORCE; then
		if sed $SED_OPTS "s@.*shellib.sh.*@$source_line@" "$source_host"
		then source_status=updated; log "forcefully updated altered source script in $source_host"; clean $source_host
		else (( errors++ )); warn "failed to update altered source script in $source_host"
		fi
	else source_status=skipped; log "found altered source script in $source_host, skipping update"
	fi

else
	if echo "$source_line" >> "$source_host"
	then source_status=appended; log "appended source script in $source_host"
	else (( errors++ )); warn "failed to append source script in $source_host"
	fi
fi

if $DIFF && ! test "$host_line" = "$source_line"
then
	cat 1>&2 <<-DIFF
	diff of source lines
	<$host_line
	---
	>$source_line
	DIFF
fi

# add spell files
for src in .vim/spell/*; do
	trg="$TRG_DIR/$src"
	if file_exists "$trg"; then
		if diff "$trg" "$src" > /dev/null
		then (( files_skipped++ )); log "$trg and $src are equal, skipping to merge"
		else
			log -n "updating spell file: $trg (..."

			if cp "$trg" "$trg~" 
			then log -ne "\b\b\bbackup,..."
			else log -e  "ERROR)"; warn "failed to backup spell file: $trg"; continue
			fi

			if cat "$src" "$trg" | sort -u > "$src".tmp; then
				log -ne "\b\b\b sorted, merged,..."

				if diff "$trg" "$src".tmp > /dev/null
				then
					log -e "\b\b\b skipped)"; (( files_skipped++ )); rm "$src".tmp
					log "$trg and merge file are equal, skipping to merge"
				elif mv "$src".tmp "$trg"
				then log -e "\b\b\b saved)"; (( files_updated++ ))
				else log -e "\b\b\b ERROR)"; (( errors++ )); warn "failed to move spell file"
				fi
			else
				log -e "ERROR)"; (( errors++ ));
				warn "spell file merge failed: $trg <- $trg\.tmp"
			fi
		fi
	else
		if mkdir -p "`dirname $trg`" && cp -u "$src" "$trg"
		then (( files_created++ )); log  "spell file copied: $src -> $trg";
		else (( errors++ ));        warn "failed to copy spell file: $src -> $trg";
		fi
	fi
done

LOG_FILE=$SRC_DIR/install.log
LOG_FILE_PREV=$SRC_DIR/install.log

# print parsable install status
# (can be be used for detecting changes, e.g., in Ansible)
cat  <<-EOF
LINKS_CREATED:  $created
LINKS_UPDATED:  $updated
LINKS_SKIPPED:  $skipped
SOURCE_SCRIPT:  $source_status
FILES_CREATED:  $files_created
FILES_UPDATED:  $files_updated
FILES_SKIPPED:  $files_skipped
ERRORS:         $errors
EOF

# print parsable status summary
if (( errors > 0 ))
then echo "INSTALLATION FAILED";    exit 1
elif (( created == 0       )) && (( updated == 0       )) &&
	  (( files_created == 0 )) && (( files_updated == 0 )) &&
	  test "$source_status" = "skipped"
then echo "INSTALLATION SKIPPED";    exit 0
else echo "INSTALLATION SUCCESSFUL"; exit 0
fi

