# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

alias browse="xdg-open ."
alias open="xdg-open"
alias :q="exit"
alias difftool="git difftool --no-prompt"
alias e="gvim --remote-silent"
alias gocover="go test -cover -covermode=count -coverprofile=cover.profile && go tool cover -html=cover.profile"

# German fun shortcuts
alias mache="make local-build"
alias baue="make build"
alias teste="make test"
alias pushe="git push"
alias pulle="git pull"

source /home/juve/.shellib/shellib.sh # generated by shellib (do not edit manually)

export GOPATH=$HOME/.gopath:$HOME/git/go #:$HOME/git/backend/vendor:$HOME/git/backend
export PATH=$PATH:$HOME/.gopath/bin
mkdir -p $HOME/.gopath

# find base16 installation either managed by Vundle in .vim
# or managed manually in .config
test -n "$BASE16_DIR" || BASE16_DIR=$HOME/.vim/bundle/base16-shell
test -d "$BASE16_DIR" || BASE16_DIR=$HOME/.config/base16-shell

if test -d "$BASE16_DIR"
then
	source "$BASE16_DIR/scripts/base16-default-dark.sh"
	if ! which colortest > /dev/null
	then
		colortest() { cd $BASE16_DIR; ./colortest $@; cd - > /dev/null; }
	fi
fi

alias run=./run.sh
alias res="./run.sh restart"
alias cmd="./run.sh cmd"

# load non-public ~/.corporaterc
test -f $HOME/.corporaterc && source $HOME/.corporaterc

# vim:ft=sh:
