# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

alias browse="xdg-open ."
alias open="xdg-open"
alias :q="exit"
alias difftool="git difftool --no-prompt"
alias e="gvim --remote-silent"
alias gocover="go test -cover -covermode=count -coverprofile=cover.profile && go tool cover -html=cover.profile"

# German fun shortcuts
alias mache="make local-build"
alias baue="make build"
alias teste="make test"
alias pushe="git push"
alias drücke="git push"
alias pulle="git pull"
alias ziehe="git pull"
alias lokale-geschwindigkeitsmessung="make local-bench"
alias zerstöre-docker='docker rm -f $(docker ps -aq) || true'
alias zerstöre-vagrant='vagrant destroy'
alias gsay="/usr/local/bin/google_speech"
alias prettyjson='python -m json.tool'
alias hadoop-screen="ssh -t name-node screen -R -s bash"
alias psql="sudo -u postgres psql"

source /home/juve/.shellib/shellib.sh # generated by shellib (do not edit manually)


# create/export a dir to store all go tools
export GOTOOLS=$HOME/.gotools
mkdir -p $GOTOOLS
addPATH $GOTOOLS/bin

export GOPATH=$GOTOOLS:$HOME/git/go

# use `setgopath` in go projects where required
alias setgopath="export GOPATH=\$PWD"

# required for eclim (not used currently)
export ECLIPSE_HOME=$HOME/apps/eclipse/java-neon
addPATH $ECLIPSE_HOME

export PYTHONDONTWRITEBYTECODE=true   # avoid having pyc files created
export PYTHONPATH="lib/python"        # look for my modules in local lib dirs

# find base16 installation either managed by Vundle in .vim
# or managed manually in .config
test -n "$BASE16_DIR" || BASE16_DIR=$HOME/.vim/bundle/base16-shell
test -d "$BASE16_DIR" || BASE16_DIR=$HOME/.config/base16-shell

if test -d "$BASE16_DIR"
then
	source "$BASE16_DIR/scripts/base16-default-dark.sh"
	if ! which colortest > /dev/null
	then
		colortest() { cd $BASE16_DIR; ./colortest $@; cd - > /dev/null; }
	fi
fi

findJDK() {
	local java_bin=`which java | xargs readlink -e | xargs dirname` 2> /dev/null &&
	readlink -e $java_bin/../..
}

random(){ shuf -i0-$1 -n1; }

passwort_gen(){ git/dotfiles/scripts/password_gen.py $@; }

export JAVA_HOME=`findJDK`

export NVM_DIR="$HOME/.nvm"
test -s "$NVM_DIR/nvm.sh" && source "$NVM_DIR/nvm.sh" # This loads nvm

# load non-public ~/.corporaterc
test -f $HOME/.corporaterc && source $HOME/.corporaterc
# load google cloud sdk
test -f $HOME/.googlerc    && source $HOME/.googlerc

# vim:ft=sh:
